Foreground yes
User clamav
LogTime yes
LogFile /var/log/clamav/clamd.log
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
LocalSocketMode 600
TCPSocket 3310
StreamMaxLength 26M
MaxFileSize 26M
MaxScanSize 100M
MaxRecursion 12
MaxFiles 1000
MaxThreads 2
MaxQueue 8
ReadTimeout 30
CommandReadTimeout 30
MaxScanTime 20000
AlertExceedsMax yes
BytecodeSecurity TrustSigned
